### ISSUE TITLE
读取不到新闻内容呢

### ISSUE THREAD

**Issue by kevinatgz** [liaozhoubei/NetEasyNews#1]
作者可以更新下代码吗？ 运行时报错
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-5
    Process: cn.bproject.neteasynews, PID: 30855
    java.lang.RuntimeException: Stub!
        at org.apache.http.message.AbstractHttpMessage.<init>(AbstractHttpMessage.java:38)
        at org.apache.http.client.methods.HttpRequestBase.<init>(HttpRequestBase.java:38)
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:39)
        at cn.bproject.neteasynews.http.HttpHelper.get(HttpHelper.java:41)
        at cn.bproject.neteasynews.fragment.news.NewsListFragment$3.run(NewsListFragment.java:209)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-03-22 11:53:24.764 30855-30855/cn.bproject.neteasynews E/RecyclerView: No adapter attached; skipping layout

**Comment by liaozhoubei** [comment]
没发现什么问题啊！
